version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=host=db;Port=5432;Database=isakdb;User Id=isak7o;Password=isakpassword;
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: isakdb
      POSTGRES_USER: isak7o
      POSTGRES_PASSWORD: isakpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  proxy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: {}
  caddy_data: {} 
  caddy_config: {} 
